Homework2
made-ml-in-prod-2021/luckyandre pull request #3
Opened 2021-05-23 20:25 UTC by LuckyAndre

см. Readme

2021-06-01 07:50 UTC, Mikhail-M requested changes
1) структура
код должен находиться в отдельной папке, как указано в условиях дз. Код тренировки не нужен для инференса
2) inference_pipeline_command -- каждый раз подгружает модель, делать такое на каждый запрос -- безумие
3) health -- каждый раз подгружает модель и трансформер и делает проверки на то, что все прогружено. 


Ввиду этих критических недостатков не смогу оценивать по пунктам на полные баллы, если не будете переделывать -- верните в работу -- что-нибудь поставлю

2021-06-05 08:09 UTC, LuckyAndre commented
Михаил, добрый день! Спасибо за комментарии. Все исправил. Проверь, пожалуйста)

2021-06-05 08:12 UTC, LuckyAndre commented
Подробная информаци по запуску/тестированию в README.

2021-06-06 10:09 UTC, Mikhail-M approved these changes
не очень понимаю, что я здесь вижу, зачем-то удален код первой дз и все в перемешку. 
Посмотрите реквествы коллег, как это должно выглядеть.

Ну да ладно.
Валидация: в таком виде не засчитывается

Баллы: 16*0.6 =9.6

2021-06-09 11:24 UTC, merged